### ISSUE TITLE
[BUG] Timeline font-weight all set to 600

### ISSUE THREAD

**Issue by jporich** [unimelb/design-system-issues#48] opened 2019-12-17 22:45 UTC
At present there is a CSS rule for Dictionary Definition (`<dd>`) elements to set `font-weight:600;`

This actually affect timelines (I'm assuming this was aimed at targeting the contact boxes we have?) When making use of a `<strong>` tag - there's no discernible difference in weight of fonts - only a veryyyy slight difference in colour (dark blue vs off-black)

Fig 1 below. All `<dd>` tags with uniform font-weight
![Screen Shot 2019-12-18 at 9 21 36 am](https://user-images.githubusercontent.com/10070570/71040468-c26ef600-217a-11ea-959c-5ad104fef01f.png)

Fig 2 below. All `<strong>` tags with same font-weight as `<dd>` and `<p>`
![Screen Shot 2019-12-18 at 9 21 18 am](https://user-images.githubusercontent.com/10070570/71040473-c69b1380-217a-11ea-9b54-7423af77aaa5.png)

Fig 3 below `<p>` tag inheriting the `<dd>` font-weight
![Screen Shot 2019-12-18 at 9 21 06 am](https://user-images.githubusercontent.com/10070570/71040486-ca2e9a80-217a-11ea-981c-deda293d5f44.png)

Fig 4 below regular `<p>` tag weight.
![Screen Shot 2019-12-18 at 9 20 48 am](https://user-images.githubusercontent.com/10070570/71040499-cdc22180-217a-11ea-81c0-6d71c94f0275.png)

## Expected behaviour

font-weight of `<p>` tags in timelines should be the same as normal `<p>` tags

## Current behaviour

`<p>` tags are set to `font-weight: 600` - should be `font-weight:400`

## Steps to reproduce

1. Insert timeline
2. In the content WYSIWYG area make use of strong tags and p tags
3. Note the font-weights

### Affected browsers
 all

## Possible solution
Create a separate rule to target general `<dd>`'s and another for timeline `<dd>`'s

**Comment by dkevey** [comment] 2019-12-17 22:54
https://law.unimelb.edu.au/students/orientation

**Comment by dkevey** [comment] 2019-12-17 23:01
looks like this class was added - can't see it in Gen 1
![image](https://user-images.githubusercontent.com/1305804/71041357-fba86580-217c-11ea-9589-841495d127fe.png)

Applying `font-weight: 400;` to `.uomcontent .timeline dd` should fix it. @jaredh-um @tomstringer could you please confirm? I can add an override CSS in the meantime.

**Comment by jaredh-um** [comment] 2019-12-17 23:37
Hi @dkevey, from what I could see of the spaghetti CSS you'd need to specify the paragraph specifically like `.uomcontent .timeline dd p` because there are a few other things in there like spans for dates that have different styling and I think applying it just to the `dd` element might change them all.

Actually I just tried dropping that whole highlighted block - which reverts everything to 400 anyway. Then the `strong` tags work as intended as well. Maybe just clear that block? Is there somewhere else the `dd` is used that we wanted it to be that bold?

**Comment by dkevey** [comment] 2019-12-17 23:45
@jaredh-um do you mean remove this class from the main CSS file? From what I can tell it wasn't there before, but I don't know why it would be added in. 
```
.uomcontent [role=main] dd {
    font-weight: 600;
}
```

**Comment by jporich** [comment] 2019-12-17 23:46
@jaredh-um @dkevey 

I can't find an example but I know we use dictionary lists `<dl>`'s in our contact-box  https://web.unimelb.edu.au/components/text/#contact-box

Can't see it in action as our DDS site hasn't got Gen 3 applied

**Comment by dkevey** [comment] 2019-12-17 23:51
Contact box has the `dd` declared like this - so it's overwritten anyway. 

https://openstage.unimelb.edu.au/home#contact
![image](https://user-images.githubusercontent.com/1305804/71043940-509baa00-2184-11ea-9707-855515497dde.png)

**Comment by jaredh-um** [comment] 2019-12-17 23:53
@jporich You can check it here while Icelab still has this deployment up:
https://unimelb-design-system-icelab.herokuapp.com/components/text

As @dkevey has said, that contact box looks like it has it's own specific styling for `.uomcontent [role="main"] .contact-box dd` so I think we could potentially drop the generic block quoted further up?

**Comment by dkevey** [comment] 2020-01-14 00:00
@jporich @jaredh-um I've added a temp css override for this in the interim. Hopefully it doesn't cause any flow on issues.

```
.uomcontent [role=main] dd {
    font-weight: 400;
}
```
https://law.unimelb.edu.au/students/orientation/_recache

**Comment by jporich** [comment] 2020-02-02 23:44
@dkevey This seems to work good now :) 

Thanks!

**Comment by dkevey** [comment] 2020-02-03 02:49
great thanks - I'll close this off

**Closed by dkevey** 2020-02-03 02:49 UTC
Labels: bug
