### ISSUE TITLE
[BUG] Weird white line floating over home banner image

### ISSUE THREAD

**Issue by rothenburycam** [unimelb/design-system-issues#12] opened 2019-11-06 04:03 UTC
There's a weird thin white line floating on top of Home Page banner images. Appears to demarcate the bottom of the navigation menu, but it would be better if it wasn't there at all.

## Expected behaviour
No white line should appear.

## Current behaviour
A white line appears over the image in both desktop and mobile.

## Steps to reproduce
![Screen Shot 2019-11-06 at 2 59 05 pm](https://user-images.githubusercontent.com/11714609/68267332-327f5c00-00a6-11ea-99fd-0335c639330d.png)
![Screen Shot 2019-11-06 at 2 58 49 pm](https://user-images.githubusercontent.com/11714609/68267334-327f5c00-00a6-11ea-81bb-071939f1deaa.png)

### Affected browsers
- [ X] Chrome

## Possible solution
Can't see where this is coming from in CSS.

**Comment by jaredh-um** [comment] 2019-11-07 00:19
Duplicate of #6, to be addressed by #84 and #95

**Closed** 2019-11-11 00:35 UTC
Labels: bug, duplicate
